name: Integration

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x, 14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: NPM install 📦
      run: npm ci
    - name: Build 🔧
      run: npm run build
    - name: ESLint ✨
      run: npm run lint
    - name: Test 🧪
      run: npm run coverage
    - name: Codecov ☂
      uses: codecov/codecov-action@v1
      with:
        directory: coverage
